word_pairs_500 = {
    "ab": "from, off",
    "Abend": "evening",
    "aber": "but",
    "acht": "eight",
    "Affe": "monkey",
    "alle": "all",
    "allein(e)": "alone",
    "als": "as, when",
    "also": "so, therefore",
    "alt": "old",
    "am": "at the",
    "an": "at, on",
    "andere": "other",
    "anfangen": "to begin, start",
    "Angst": "fear",
    "antworten (beantworten)": "to answer (respond)",
    "Apfel": "apple",
    "Arbeit": "work",
    "arbeiten": "to work",
    "Arzt": "doctor",
    "auch": "also, too",
    "auf": "on, upon",
    "Auge(n)": "eye(s)",
    "aus": "from, out of",
    "Auto": "car",
    "baden": "to bathe",
    "bald": "soon",
    "Ball": "ball",
    "bauen": "to build",
    "Bauer": "farmer",
    "Baum": "tree",
    "bei": "at, by, near",
    "beide": "both",
    "beim (bei dem)": "at the",
    "Bein": "leg",
    "Beispiel": "example",
    "beißen": "to bite",
    "bekommen": "to receive, get",
    "Berg": "mountain",
    "besser": "better",
    "Bett": "bed",
    "Bild": "picture, image",
    "bin": "am (I am)",
    "bis": "until, by",
    "blau": "blue",
    "bleiben": "to stay, remain",
    "Blume": "flower",
    "Boden": "floor, ground",
    "böse": "evil, angry",
    "brauchen": "to need",
    "braun": "brown",
    "Brief": "letter",
    "bringen": "to bring",
    "Brot": "bread",
    "Bruder": "brother",
    "Buch": "book",
    "da": "there",
    "dabei": "with it, thereby",
    "dafür": "for it",
    "damit": "with it",
    "danach": "after that",
    "dann": "then",
    "daran": "on it, about it",
    "darauf": "on it",
    "darin": "in it",
    "das": "the, that",
    "dauern": "to last, take (time)",
    "davon": "of it, about it",
    "dazu": "to it, in addition",
    "dein": "your (singular informal)",
    "dem": "the (dative neuter or masculine)",
    "den": "the (accusative masculine or plural)",
    "denken": "to think",
    "denn": "because, for",
    "der": "the (nominative masculine)",
    "deshalb": "therefore",
    "dich": "you (accusative singular informal)",
    "dick": "fat, thick",
    "die": "the (nominative feminine or plural)",
    "Ding": "thing",
    "dir": "you (dative singular informal)",
    "doch": "however, yet",
    "Dorf": "village",
    "dort": "there",
    "draußen": "outside",
    "drehen": "to turn",
    "drei": "three",
    "dumm": "stupid",
    "dunkel": "dark",
    "durch": "through",
    "dürfen": "may, to be allowed",
    "eigentlich": "actually",
    "ein": "a, an (masculine)",
    "eine": "a, an (feminine)",
    "einer": "a, an (neuter)",
    "einfach": "simple, easy",
    "einige": "some, a few",
    "einigen": "to agree",
    "einmal": "once",
    "Eis": "ice, ice cream",
    "Eltern": "parents",
    "Ende": "end",
    "endlich": "finally",
    "er": "he",
    "Erde": "earth, ground",
    "erklären": "to explain",
    "erschrecken": "to frighten, scare",
    "erst": "first, only",
    "erzählen": "to tell, narrate",
    "es": "it",
    "essen": "to eat",
    "Essen": "food",
    "etwas": "something",
    "fahren": "to drive, ride, go",
    "Fahrrad": "bicycle",
    "fährt": "drives, goes",
    "fallen": "to fall",
    "Familie": "family",
    "fangen": "to catch",
    "fast": "almost",
    "fehlen": "to lack, be missing",
    "Fenster": "window",
    "Ferien": "vacation, holidays",
    "fertig": "finished, ready",
    "fest": "firm, solid",
    "Feuer": "fire",
    "fiel": "fell",
    "finden": "to find",
    "Finger": "finger",
    "Fisch": "fish",
    "Flasche": "bottle",
    "fliegen": "to fly",
    "Frage": "question",
    "fragen": "to ask",
    "Frau": "woman, Mrs.",
    "frei": "free",
    "fressen": "to eat (for animals)",
    "Freude": "joy",
    "freuen": "to be glad, rejoice",
    "Freund": "friend",
    "fröhlich": "cheerful",
    "früh": "early",
    "früher": "earlier, in the past",
    "führen": "to lead, conduct",
    "fünf": "five",
    "für": "for",
    "Fuß": "foot",
    "Fußball": "soccer, football",
    "gab": "gave",
    "ganz": "whole, entire",
    "gar": "at all, even",
    "Garten": "garden",
    "geben": "to give",
    "Geburtstag": "birthday",
    "gefährlich": "dangerous",
    "gegen": "against",
    "gehen": "to go, walk",
    "gehören": "to belong",
    "gelb": "yellow",
    "Geld": "money",
    "genau": "exactly",
    "gerade": "straight, just now",
    "gern(e)": "gladly, like to",
    "Geschenk": "gift",
    "Geschichte": "story, history",
    "Gesicht": "face",
    "gestern": "yesterday",
    "gesund": "healthy",
    "gewinnen": "to win",
    "gibt": "gives",
    "ging": "went",
    "Glas": "glass",
    "glauben": "to believe",
    "gleich": "same, immediately",
    "Glück": "luck, fortune",
    "glücklich": "happy, fortunate",
    "Gott": "God",
    "groß(e)": "big, large, tall",
    "grün": "green",
    "gut": "good",
    "Haar(e)": "hair",
    "haben": "to have",
    "halb(e)": "half",
    "halten": "to hold, keep",
    "Hand": "hand",
    "hängen": "to hang",
    "hart": "hard",
    "Hase": "rabbit",
    "hat": "has",
    "hatte": "had",
    "hatten": "had (plural)",
    "Haus": "house",
    "heiß": "hot",
    "heißen": "to be called",
    "helfen": "to help",
    "her": "here, towards",
    "heraus": "out, from",
    "Herr": "Mr., gentleman",
    "Herz": "heart",
    "heute": "today",
    "hier": "here",
    "Hilfe": "help",
    "Himmel": "sky, heaven",
    "hin": "to there",
    "hinein": "into",
    "hinter": "behind",
    "hoch": "high, tall",
    "holen": "to fetch, get",
    "hören": "to hear",
    "Hund": "dog",
    "Hunger": "hunger",
    "ich": "I",
    "ihm": "him (dative)",
    "ihn": "him (accusative)",
    "ihr": "her, their, you (plural informal)",
    "im": "in the",
    "immer": "always",
    "in": "in",
    "ins": "into the",
    "ist": "is",
    "ja": "yes",
    "Jahr": "year",
    "jeder": "everyone, each",
    "jetzt": "now",
    "jung": "young",
    "Junge": "boy",
    "kalt": "cold",
    "kam": "came",
    "kann": "can, to be able to",
    "Katze": "cat",
    "kaufen": "to buy",
    "kein": "no, not any",
    "kennen": "to know (a person)",
    "Kind": "child",
    "Klasse": "class",
    "klein": "small, little",
    "klettern": "to climb",
    "kochen": "to cook",
    "kommen": "to come",
    "können": "can, to be able to",
    "Kopf": "head",
    "krank": "sick, ill",
    "Küche": "kitchen",
    "kurz": "short",
    "lachen": "to laugh",
    "Land": "country, land",
    "lang(e)": "long",
    "langsam": "slow, slowly",
    "las": "read (past tense of 'lesen')",
    "lassen": "to let, allow",
    "laufen": "to run, walk",
    "laut": "loud",
    "leben": "to live",
    "Leben": "life",
    "legen": "to lay, put",
    "Lehrer": "teacher (male)",
    "Lehrerin": "teacher (female)",
    "leicht": "light, easy",
    "leise": "quiet, soft",
    "lernen": "to learn",
    "lesen": "to read",
    "letzte": "last",
    "Leute": "people",
    "Licht": "light",
    "lieb": "dear, kind",
    "liegen": "to lie, be situated",
    "ließ(en)": "let, left (past tense of 'lassen')",
    "Loch": "hole",
    "los": "go, start",
    "Luft": "air",
    "lustig": "funny, amusing",
    "machen": "to make, do",
    "Mädchen": "girl",
    "mal": "time (as in 'once upon a time')",
    "man": "one, people, they",
    "Mann": "man",
    "Maus": "mouse",
    "Meer": "sea",
    "mehr": "more",
    "mein": "my",
    "Mensch": "human, person",
    "merken": "to notice, remember",
    "mich": "me (accusative)",
    "Milch": "milk",
    "Minute(n)": "minute(s)",
    "mir": "me (dative)",
    "mit": "with",
    "mögen": "to like",
    "möglich": "possible",
    "Monat(e)": "month(s)",
    "müde": "tired",
    "Musik": "music",
    "müssen": "must, to have to",
    "Mutter": "mother",
    "Mutti": "mom",
    "nach": "after, to",
    "nächste": "next",
    "Nacht": "night",
    "nah(e)": "near",
    "Name(n)": "name(s)",
    "nämlich": "namely, that is to say",
    "Nase": "nose",
    "nass": "wet",
    "natürlich": "naturally, of course",
    "neben": "next to",
    "nehmen": "to take",
    "nein": "no",
    "nennen": "to call, name",
    "neu": "new",
    "neun": "nine",
    "nicht": "not",
    "nichts": "nothing",
    "nie": "never",
    "nimmt": "takes",
    "noch": "still, yet",
    "nun": "now",
    "nur": "only",
    "ob": "whether, if",
    "oben": "up, above",
    "oder": "or",
    "offen": "open",
    "öffnen": "to open",
    "oft": "often",
    "ohne": "without",
    "Oma": "grandma",
    "Omi": "granny",
    "Onkel": "uncle",
    "Opa": "grandpa",
    "packen": "to pack, grasp",
    "Pferd": "horse",
    "Platz": "place, square",
    "plötzlich": "suddenly",
    "Polizei": "police",
    "Rad": "wheel, bike",
    "rechnen": "to calculate, reckon",
    "reich": "rich",
    "reiten": "to ride (a horse)",
    "rennen": "to run",
    "richtig": "right, correct",
    "rot": "red",
    "rufen": "to call, shout",
    "ruhig": "calm, quiet",
    "rund": "round, around",
    "Sache": "thing, matter",
    "sagen": "to say",
    "schaffen": "to manage, create",
    "schauen": "to look, watch",
    "scheinen": "to seem, shine",
    "schenken": "to give (as a gift)",
    "schicken": "to send",
    "Schiff": "ship",
    "schlafen": "to sleep",
    "schlagen": "to hit, beat",
    "schlecht": "bad",
    "schlimm": "bad, serious",
    "Schluss": "end, conclusion",
    "Schnee": "snow",
    "schnell": "fast, quick",
    "schon": "already",
    "schön": "beautiful, nice",
    "schreiben": "to write",
    "schreien": "to scream, shout",
    "Schuh": "shoe",
    "Schule": "school",
    "Schüler": "student, pupil",
    "schwarz": "black",
    "schwer": "heavy, difficult",
    "Schwester": "sister",
    "schwimmen": "to swim",
    "sechs": "six",
    "See": "lake, sea",
    "sehen": "to see",
    "sehr": "very",
    "sein": "to be",
    "seit": "since",
    "Seite": "side, page",
    "selbst": "self, even",
    "setzen": "to set, put",
    "sich": "oneself",
    "sicher": "sure, safe",
    "sie": "she, they, you (formal)",
    "sieben": "seven",
    "sieht": "sees",
    "sind": "are",
    "singen": "to sing",
    "sitzen": "to sit",
    "so": "so, such",
    "sofort": "immediately",
    "Sohn": "son",
    "sollen": "should, ought to",
    "Sommer": "summer",
    "Sonne": "sun",
    "Sonntag": "Sunday",
    "sonst": "otherwise, else",
    "Spaß": "fun",
    "spät": "late",
    "später": "later",
    "Spiel": "game",
    "spielen": "to play",
    "sprechen": "to speak",
    "springen": "to jump",
    "Stadt": "city",
    "stark": "strong",
    "stehen": "to stand",
    "steigen": "to climb, rise",
    "Stein": "stone",
    "Stelle": "place, spot",
    "stellen": "to put, place",
    "Straße": "street",
    "Stück": "piece",
    "Stunde": "hour",
    "suchen": "to search, look for",
    "Tag": "day",
    "Tante": "aunt",
    "Teller": "plate",
    "tief": "deep",
    "Tier": "animal",
    "Tisch": "table",
    "tot": "dead",
    "tragen": "to carry, wear",
    "traurig": "sad",
    "treffen": "to meet, hit",
    "trinken": "to drink",
    "tun": "to do",
    "Tür": "door",
    "turnen": "to do gymnastics",
    "über": "over, above",
    "überall": "everywhere",
    "Uhr": "clock, watch",
    "um": "around, at (time)",
    "und": "and",
    "uns": "us",
    "unser": "our",
    "unten": "below, downstairs",
    "unter": "under, beneath",
    "Vater": "father",
    "Vati": "dad",
    "vergessen": "to forget",
    "verkaufen": "to sell",
    "verlieren": "to lose",
    "verstecken": "to hide",
    "verstehen": "to understand",
    "versuchen": "to try",
    "viel": "much, many",
    "vielleicht": "maybe, perhaps",
    "vier": "four",
    "Vogel": "bird",
    "voll": "full",
    "vom": "from the",
    "von": "from, of",
    "vor": "before, in front of",
    "vorbei": "past, over",
    "Wagen": "car",
    "wahr": "true",
    "Wald": "forest",
    "war": "was",
    "waren": "were",
    "warm": "warm",
    "warten": "to wait",
    "warum": "why",
    "was": "what",
    "waschen": "to wash",
    "Wasser": "water",
    "weg": "away",
    "Weg": "way, path",
    "Weihnachten": "Christmas",
    "weil": "because",
    "weinen": "to cry",
    "weiß": "white, know",
    "weit": "far",
    "weiter": "further",
    "Welt": "world",
    "wenig": "little, few",
    "wenn": "if, when",
    "wer": "who",
    "werden": "to become, will (future tense)",
    "werfen": "to throw",
    "Wetter": "weather",
    "wichtig": "important",
    "wie": "how, like, as",
    "wieder": "again",
    "Wiese": "meadow",
    "will": "wants to",
    "Winter": "winter",
    "wir": "we",
    "wird": "will (future tense of 'to be')",
    "wirklich": "really, actually",
    "wissen": "to know",
    "wo": "where",
    "Woche": "week",
    "wohl": "well, probably",
    "wohnen": "to live (reside)",
    "Wohnung": "apartment",
    "wollen": "to want",
    "Wort": "word",
    "wünschen": "to wish",
    "Zahl": "number",
    "zehn": "ten",
    "zeigen": "to show",
    "Zeit": "time",
    "Zeitung": "newspaper",
    "ziehen": "to pull, move",
    "Zimmer": "room",
    "zu": "to, too",
    "Zug": "train",
    "zum": "to the (contraction of 'zu dem')",
    "zur": "to the (contraction of 'zu der')",
    "zurück": "back",
    "zusammen": "together",
    "zwei": "two",
    "zwischen": "between"
}